spring.application.name=springSecurity

spring.security.user.name=jaydev
spring.security.user.password=mahato

spring.datasource.url=jdbc:postgresql://localhost:5432/SecuityLearning
spring.datasource.username=********
spring.datasource.password=********

#This will create schema on running your application and will also drop all schemas once you stop your application
spring.jpa.hibernate.ddl-auto=update

#To see all the sql statements run by hibernate
spring.jpa.show-sql=true

#Format the hibernate queries, statements
spring.jpa.properties.hibernate.format_sql=true